version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./projecto_failai/public_html:/usr/share/nginx/html
    networks:
      - webnet
networks:
  webnet: